-- V3 Phase 1: activity logging + soft-delete support
-- Safe to run once in Supabase SQL editor or migration pipeline.

-- 1) Add archived_at for soft-delete workflow.
alter table if exists public.companies
  add column if not exists archived_at timestamptz;

alter table if exists public.users
  add column if not exists archived_at timestamptz;

alter table if exists public.sites
  add column if not exists archived_at timestamptz;

alter table if exists public.shifts
  add column if not exists archived_at timestamptz;

create index if not exists companies_archived_at_idx on public.companies (archived_at);
create index if not exists users_archived_at_idx on public.users (archived_at);
create index if not exists sites_archived_at_idx on public.sites (archived_at);
create index if not exists shifts_archived_at_idx on public.shifts (archived_at);

-- 2) Activity log table for audit timeline.
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  entity text not null,
  entity_id text,
  details text,
  created_at timestamptz not null default now()
);

create index if not exists activity_logs_created_at_idx
  on public.activity_logs (created_at desc);

-- 3) Enable RLS and basic policies.
alter table public.activity_logs enable row level security;

drop policy if exists "Authenticated users can read activity logs" on public.activity_logs;
create policy "Authenticated users can read activity logs"
on public.activity_logs
for select
to authenticated
using (true);

drop policy if exists "Authenticated users can insert activity logs" on public.activity_logs;
create policy "Authenticated users can insert activity logs"
on public.activity_logs
for insert
to authenticated
with check (true);
